//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliCanEntry
    {
        public int ID { get; set; }
        public string AccountUser { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Favorite { get; set; }
        public string Location { get; set; }
        public string HasApplied { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<System.DateTime> DateAppCloses { get; set; }
        public string HasInterview { get; set; }
        public Nullable<System.DateTime> DateInterview { get; set; }
        public string HasOffer { get; set; }
        public string OfferNotes { get; set; }
        public Nullable<System.DateTime> DateOfferGiven { get; set; }
        public Nullable<System.DateTime> DateOfferDeadline { get; set; }
        public string ContactInfo { get; set; }
        public string PositionNotes { get; set; }
        public string CompanyNotes { get; set; }
        public Nullable<int> Enabled { get; set; }
    }
}
