//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliCan {
	
	
	public partial class PopUp1 {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label TitleName;
		
		protected System.Web.UI.WebControls.Label JobTCompN;
		
		protected System.Web.UI.WebControls.Label DueDate;
		
		protected System.Web.UI.WebControls.Label DateApplied;
		
		protected System.Web.UI.WebControls.Label AskedforInterview;
		
		protected System.Web.UI.WebControls.Label OfferInfo;
		
		protected System.Web.UI.WebControls.Label Deadline;
		
		protected System.Web.UI.WebControls.Label Notes;
	}
}
