//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsaState
    {
        public int ID { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string IsRealState { get; set; }
        public string StateDate { get; set; }
    }
}
